In [1]:
import tensorflow as tf

In [2]:
from tensorflow.keras.preprocessing.text import one_hot
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am good developer',
      'understand the meaning of word',
      'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am good developer',
 'understand the meaning of word',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=1000


In [5]:
## One hot representation for every word
one_hot_representation=[one_hot(word,voc_size) for word in sent]


In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am good developer',
 'understand the meaning of word',
 'your videos are good']

In [ ]:

one_hot_representation

[[944, 772, 322, 586],
 [944, 772, 322, 485],
 [944, 860, 322, 136],
 [451, 295, 919, 117, 413],
 [451, 295, 117, 560],
 [230, 944, 757, 322, 618],
 [131, 964, 519, 117]]

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [ ]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_representation,padding='pre',maxlen=sent_length)

In [13]:
print(embedded_docs)

[[  0   0   0   0 944 772 322 586]
 [  0   0   0   0 944 772 322 485]
 [  0   0   0   0 944 860 322 136]
 [  0   0   0 451 295 919 117 413]
 [  0   0   0   0 451 295 117 560]
 [  0   0   0 230 944 757 322 618]
 [  0   0   0   0 131 964 519 117]]


In [14]:
## Feature Representation
dim=10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             10000     
                                                                 
Total params: 10000 (39.06 KB)
Trainable params: 10000 (39.06 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 271ms/step


array([[[ 0.03896211, -0.01305318,  0.04814802, -0.03750124,
         -0.02248055,  0.01959392,  0.02161754,  0.02376494,
         -0.04473985, -0.0016454 ],
        [ 0.03896211, -0.01305318,  0.04814802, -0.03750124,
         -0.02248055,  0.01959392,  0.02161754,  0.02376494,
         -0.04473985, -0.0016454 ],
        [ 0.03896211, -0.01305318,  0.04814802, -0.03750124,
         -0.02248055,  0.01959392,  0.02161754,  0.02376494,
         -0.04473985, -0.0016454 ],
        [ 0.03896211, -0.01305318,  0.04814802, -0.03750124,
         -0.02248055,  0.01959392,  0.02161754,  0.02376494,
         -0.04473985, -0.0016454 ],
        [-0.03855409, -0.02474848, -0.01819795,  0.04860293,
          0.02316697,  0.00666568, -0.02998722, -0.03341736,
          0.00670648, -0.03832486],
        [ 0.03590571,  0.04899717,  0.00730272, -0.0424209 ,
         -0.02582029,  0.03237058, -0.00806063,  0.04858228,
         -0.03539247,  0.03353054],
        [-0.00245308,  0.0014824 ,  0.00122243,  0.0

In [18]:
embedded_docs[0]

array([  0,   0,   0,   0, 944, 772, 322, 586])

In [20]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 75ms/step


array([[ 0.03896211, -0.01305318,  0.04814802, -0.03750124, -0.02248055,
         0.01959392,  0.02161754,  0.02376494, -0.04473985, -0.0016454 ],
       [ 0.03896211, -0.01305318,  0.04814802, -0.03750124, -0.02248055,
         0.01959392,  0.02161754,  0.02376494, -0.04473985, -0.0016454 ],
       [ 0.03896211, -0.01305318,  0.04814802, -0.03750124, -0.02248055,
         0.01959392,  0.02161754,  0.02376494, -0.04473985, -0.0016454 ],
       [ 0.03896211, -0.01305318,  0.04814802, -0.03750124, -0.02248055,
         0.01959392,  0.02161754,  0.02376494, -0.04473985, -0.0016454 ],
       [-0.03855409, -0.02474848, -0.01819795,  0.04860293,  0.02316697,
         0.00666568, -0.02998722, -0.03341736,  0.00670648, -0.03832486],
       [ 0.03590571,  0.04899717,  0.00730272, -0.0424209 , -0.02582029,
         0.03237058, -0.00806063,  0.04858228, -0.03539247,  0.03353054],
       [-0.00245308,  0.0014824 ,  0.00122243,  0.0271562 , -0.02000665,
        -0.00463582,  0.03262218, -0.02544518